version: "3.9"

services:
  db:
    image: postgres
    env_file: project/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: .
#    entrypoint: docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A project worker -l info
    depends_on:
      - backend
      - redis
      - db
volumes:
  postgres_data: